spring.application.name=todo-management

# Database properties
spring.datasource.url=jdbc:mysql://localhost:3306/todo_management
spring.datasource.username=root
spring.datasource.password=Himalaya@787375

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show_sql=true
spring.jpa.hibernate.format_sql=true

# Logging and Debugging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE

# Spring security credentials
#spring.security.user.name=himalaya
#spring.security.user.password=password
#spring.security.user.roles=ADMIN, USER, MANAGER